[package]
name = "init_task"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "4.4.7", features = ["derive"] }
path-clean = "1.0.1"
regex = "1.10.2"
whoami = "1.4.1"

